[package]
name = "trajectory"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
clap = { version = "4.5.23", features = ["derive"] }
crossterm = "0.28.1"
log = "0.4.22"
pretty_env_logger = "0.5.0"
ratatui = "0.29.0"

